### ISSUE TITLE
AI柠檬网站链接跳转异常

### ISSUE THREAD

**Issue by hgneng** [nl8590687/Machine-Learning-Tutorial-Chinese#1]
你昨天改了一下网站之后，现在提交评论会跳转到下面这样的地址。网站里很多链接都会跳转到类似的地址。
http://127.0.0.1/#comment-2266

**Comment by nl8590687** [comment]
我刚才看了一下，好像是防火墙抽风了，自己更新了规则，您现在可以再试试

**Comment by hgneng** [comment]
已验证网站恢复正常。
